require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "examples/**/*"

# Allow longer lines in specs
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

# Keyword args are fine for value objects with many fields
Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - "spec/workflow_spec.rb"

Naming/MethodParameterName:
  Enabled: false

