---
name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Please describe the feature you'd like.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it enable?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working? Include API examples if applicable.
      render: ruby

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Client
        - Worker
        - Testing
        - Middleware
        - Documentation
        - Other
